export type SystemId = 'skeletal'|'muscular'|'arterial'|'venous'|'nervous'|'digestive'|'respiratory'|'urinary'|'reproductive'|'lymphatic'|'endocrine'|'integumentary'|'connective'|'sensory'|'cardiac';
export const SYSTEMS: {id:SystemId;name:string;color:string;description:string}[] = [
 {id:'skeletal',name:'İskelet',color:'#e2d9ba',description:'Kemikler vücudun taşıyıcı iskeletini oluşturur, organları korur ve kaslara tutunma noktaları sağlar. İç dokuları ayrıca mineral depolar ve kan hücreleri üretir.'},
 {id:'muscular',name:'Kaslar',color:'#a85b50',description:'İskelet kasları, tutundukları noktaları çekerek hareket üretir. Kirişlerle birlikte eklemleri hareket ettirir, duruşu dengede tutar ve ısı üretir.'},
 {id:'cardiac',name:'Kalp',color:'#b96760',description:'Kalp, dört odacıklı kaslı bir pompadır. Kapakları, kanı pulmoner ve sistemik dolaşım boyunca ileri yönde yönlendirir.'},
 {id:'sensory',name:'Duyu Organları',color:'#b0c8ce',description:'Bu yapılar görme, işitme ve denge gibi özel duyulara katkıda bulunur. Özelleşmiş dokuları uyaranları algılar ve bilgiyi iletmek için sinir sistemiyle birlikte çalışır.'},
 {id:'arterial',name:'Atardamarlar',color:'#c05245',description:'Kalp, kanı dolaşım boyunca pompalar. Atardamarlar kanı kalpten dokulara, ya da pulmoner dolaşımda akciğerlere taşır.'},
 {id:'venous',name:'Toplardamarlar',color:'#527c9f',description:'Toplardamarlar kanı kalbe geri taşır. Yüzeysel ve derin ağlar dokulardan kan toplar; pulmoner venler akciğerlerden oksijenli kanı geri getirir.'},
 {id:'nervous',name:'Sinir Sistemi',color:'#d8b565',description:'Beyin, omurilik ve çevresel sinirler sinyalleri taşır ve işler. Duyum, hareket, koordinasyon ve vücut işlevlerinin otomatik düzenlenmesini destekler.'},
 {id:'respiratory',name:'Solunum',color:'#b98991',description:'Hava yolları havayı akciğerlere taşır; burada oksijen ve karbondioksit hava ile kan arasında yer değiştirir. Nefes alma, solunum kaslarının oluşturduğu basınç değişimlerine bağlıdır.'},
 {id:'digestive',name:'Sindirim',color:'#b8916b',description:'Sindirim sistemi besinleri parçalar, besin maddelerini ve suyu emer, atığı ileri taşır. Yardımcı organlar safra ve sindirim enzimleri sağlar.'},
 {id:'urinary',name:'Boşaltım',color:'#b47961',description:'Böbrekler kanı süzer, sıvı, elektrolit ve asit-baz dengesini düzenler. İdrar, üreterler yoluyla mesaneye ulaşır ve üretradan dışarı atılır.'},
 {id:'lymphatic',name:'Lenfatik',color:'#879f7c',description:'Lenf damarları fazla doku sıvısını dolaşıma geri döndürür. Lenf düğümleri ve diğer lenfoid organlar bağışıklık gözetimini ve yanıtlarını destekler.'},
 {id:'endocrine',name:'Endokrin',color:'#c5a09a',description:'Endokrin organlar, metabolizma, büyüme, stres yanıtları ve üreme gibi süreçleri koordine etmek için kana hormon salgılar.'},
 {id:'reproductive',name:'Üreme',color:'#bda098',description:'Burada gösterilen erkek üreme yapıları, sperm üretimi, olgunlaşması, taşınması ve cinsiyet hormonlarının üretimine katkıda bulunur.'},
 {id:'integumentary',name:'Vücut Yüzeyi',color:'#ba9b7d',description:'Vücut yüzeyi dışa dönük bir anatomik referans sağlar. Örtü sistemi koruyucu bir bariyer oluşturur, duyum ve sıcaklık düzenlemesine katkıda bulunur.'},
 {id:'connective',name:'Bağ Doku',color:'#aec3bb',description:'Kıkırdak, bağlar ve diğer bağ dokuları yapıları destekler, birbirine bağlar ve ayırır. Eklemleri sabitlemek ve mekanik yükleri dağıtmak bu dokuların görevleri arasındadır.'},
];
export interface Part {id:string;name:string;conceptId:string;system:SystemId;chunk:number;positions:number;normals:number;indices:number;vertexCount:number;indexCount:number;bounds:[number[],number[]]}
export interface Concept {id:string;name:string;elements:string[]}
export interface Atlas {version:string;sex?:'male';source?:string;scope?:string;parts:Part[];concepts:Concept[];chunks:{url:string;bytes:number;gzip?:string;gzipBytes?:number}[];triangles:number}
export type View = 'three-quarter'|'front'|'back'|'side';
export type CrossAxis = 'none'|'top'|'side';
export interface SceneState {inspectorOpen?:boolean;explode:number;visible:SystemId[];selected:string[];isolate:boolean;view:View;rotate:boolean;reset:number;cross:CrossAxis;crossAmount:number;crossInvert:boolean;highlightColor:string|null}
export const HIGHLIGHT_COLORS:{id:string;label:string;hex:string}[] = [
 {id:'teal',label:'Turkuaz',hex:'#6bd9c7'},
 {id:'red',label:'Kırmızı',hex:'#e0483e'},
 {id:'orange',label:'Turuncu',hex:'#e0923e'},
 {id:'yellow',label:'Sarı',hex:'#e0c23e'},
 {id:'green',label:'Yeşil',hex:'#4caf6e'},
 {id:'blue',label:'Mavi',hex:'#4a90d9'},
 {id:'purple',label:'Mor',hex:'#9b6bd9'},
];
export const DEFAULT_VISIBLE:SystemId[] = ['cardiac','sensory','skeletal','muscular','arterial','venous','nervous','respiratory','digestive','urinary','lymphatic','endocrine','reproductive','connective'];
// Anahtarlar atlas verisindeki İngilizce/Latince yapı adlarıyla eşleşir (küçük harf) — bunlar değiştirilmez.
// Açıklama metinleri Türkçedir.
export const EXPLANATIONS:Record<string,string> = {
 'heart':'Göğüste bulunan kaslı bir pompa. Sağ tarafı kanı akciğerlere, sol tarafı ise kanı sistemik dolaşıma gönderir.',
 'liver':'Diyaframın sağ tarafının altında yer alan büyük bir organ. Emilen besinleri işler, safra üretir ve kanda taşınan birçok proteini sentezler.',
 'brain':'Sinir sisteminin merkezi organı. Birbirine bağlı bölgeleri algı, hareket, hafıza, dil ve vücut işlevlerinin düzenlenmesini destekler.',
 'stomach':'Yemek borusu ile ince bağırsak arasında yer alan kaslı bir odacık. Besinleri asit ve enzimlerle karıştırıp depolar, ardından onikiparmak bağırsağına gönderir.',
 'spleen':'Karnın sol üst kısmında yer alan lenfoid bir organ. Kanı süzer, yaşlanan kan hücrelerini temizler ve bağışıklık yanıtlarına katılır.',
 'pancreas':'Hem sindirim hem endokrin görevleri olan karın içi bir organ. İnce bağırsağa enzim sağlar, insülin ve glukagon gibi hormonlar salgılar.',
 'urinary bladder':'Böbreklerden üreterler yoluyla gelen idrarı depolayan, pelviste yer alan kaslı bir hazne.',
 'trachea':'Gırtlağı bronşlara bağlayan ana hava yolu. Kıkırdak halkaları, nefes alırken hava yolunun açık kalmasını sağlar.',
 'diaphragm':'Göğüs ile karın boşluğunu ayıran geniş bir kas. Kasıldığında göğüs hacmini artırarak akciğerlere hava çekilmesine yardımcı olur.',
 'kidney':'Belin arkasında, omurganın iki yanında yer alan çift organ. Kanı süzerek atık maddeleri ve fazla sıvıyı idrar olarak uzaklaştırır, kan basıncı ve elektrolit dengesini düzenler.',
 'left kidney':'Belin arkasında, omurganın sol tarafında yer alan böbrek. Kanı süzerek atık maddeleri idrar olarak uzaklaştırır, kan basıncı ve elektrolit dengesini düzenler.',
 'right kidney':'Belin arkasında, omurganın sağ tarafında yer alan böbrek. Kanı süzerek atık maddeleri idrar olarak uzaklaştırır, kan basıncı ve elektrolit dengesini düzenler.',
 'left lung':'Göğüs kafesinin sol tarafında yer alan, solunumun gerçekleştiği sünger benzeri organ. Kalbe yer açmak için sağ akciğerden daha küçüktür ve iki loba ayrılır.',
 'right lung':'Göğüs kafesinin sağ tarafında yer alan, solunumun gerçekleştiği sünger benzeri organ. Sol akciğerden daha büyüktür ve üç loba ayrılır.',
 'esophagus':'Yutağı mideye bağlayan kaslı boru. Yutma sırasında kasılarak besini mideye doğru iter.',
 'small intestine':'Mideden büyük bağırsağa uzanan, besinlerin büyük kısmının sindirilip emildiği uzun, kıvrımlı organ; onikiparmak bağırsağı, jejunum ve ileum bölümlerinden oluşur.',
 'large intestine':'İnce bağırsaktan gelen sindirilmiş içerikten suyu ve elektrolitleri emen, dışkının oluştuğu ve depolandığı organ.',
 'gallbladder':'Karaciğerin altında yer alan, karaciğerin ürettiği safrayı depolayıp yoğunlaştıran küçük kese; yağlı besinler alındığında safrayı onikiparmak bağırsağına salgılar.',
 'femur':'Vücudun en uzun ve en güçlü kemiği; kalça ile diz eklemleri arasında uzanır, yürüme ve ayakta durma sırasında vücut ağırlığının büyük bölümünü taşır.',
 'tibia':'Bacağın iç tarafında yer alan, ağırlık taşıyan ana kemik. Dizden ayak bileğine uzanır ve femurla diz ekleminde birleşir.',
 'fibula':'Bacağın dış tarafında, tibiaya paralel uzanan ince kemik. Ağırlık taşımaktan çok kaslara tutunma yüzeyi sağlar ve ayak bileği ekleminin dış desteğini oluşturur.',
 'humerus':'Kolun tek kemiği; omuzdan dirseğe uzanır. Üst ucu omuz eklemini, alt ucu dirsek eklemini oluşturur.',
 'radius':'Önkolun başparmak tarafındaki kemiği. Dirsekten bileğe uzanır ve ulna ile birlikte önkolun dönme hareketini sağlar.',
 'ulna':'Önkolun serçe parmak tarafındaki, dirsek eklemini oluşturan uzun kemik.',
 'skull':'Beyni koruyan kemik yapı; kraniyum (beyin kutusu) ve yüz kemiklerinden oluşur. Çok sayıda kemiğin dikişlerle (sütur) birleşmesinden meydana gelir.',
 'vertebra':'Omurgayı oluşturan tekil kemik halkalarından her biri. Omuriliği korur, gövdeyi taşır ve komşu omurlarla eklemler yaparak esnekliği sağlar.',
 'pelvis':'Omurga ile bacakları birbirine bağlayan, leğen şeklindeki kemik halka. İç organları korur ve vücut ağırlığını bacaklara aktarır.',
 'scapula':'Sırtın üst kısmında, göğüs kafesinin arkasında yer alan üçgen şeklinde düz kemik. Omuz ekleminin bir parçasıdır ve kolun/sırtın birçok kasına tutunma yüzeyi sağlar.',
 'clavicle':'Göğüs kemiği ile kürek kemiğini birbirine bağlayan uzun, S şeklinde kemik. Kolu gövdeye bağlayan tek kemiksel köprüdür.',
 'sternum':'Göğsün ön orta hattında yer alan düz kemik. Kaburga kıkırdakları aracılığıyla kaburgalarla birleşerek göğüs kafesinin ön duvarını oluşturur.',
 'rib':'Göğüs kafesini oluşturan, omurgadan göğüs kemiğine doğru kavis çizen kemiklerden her biri; toplam 12 çift bulunur ve kalp, akciğer gibi organları korur.',
 'aorta':'Vücudun en büyük atardamarı. Sol karıncıktan çıkar, göğüs ve karından geçerek kanı tüm vücuda dağıtan dallara ayrılır.',
 'larynx':'Yutak ile soluk borusu arasında yer alan, ses tellerini barındıran kıkırdak yapı. Konuşma sesini üretir ve yutma sırasında yiyeceğin hava yoluna kaçmasını önler.',
 'pharynx':'Burun ve ağız boşluklarını gırtlak ve yemek borusuna bağlayan kaslı boru. Hem solunum hem sindirim yolunun ortak geçiş bölgesidir.',
 'tongue':'Ağız boşluğundaki kaslı organ; besinleri çiğneme sırasında hareket ettirir, yutmaya yardımcı olur, tat alma ve konuşmada görev yapar.',
 'testis':'Erkek üreme sistemi organı; sperm üretimini ve testosteron hormonu salgısını gerçekleştirir.',
 'prostate':'Mesanenin hemen altında, üretrayı çevreleyen bez. Meninin bir kısmını oluşturan sıvıyı salgılar.',
 'patella':'Diz ekleminin önünde yer alan, quadriceps kasının kirişi içine gömülü küçük, yuvarlak kemik. Diz eklemini önden korur ve kasın kaldıraç etkisini artırır.',
 'mandible':'Yüzün tek hareketli kemiği; alt dişleri taşır ve çiğneme kaslarının etkisiyle ağzın açılıp kapanmasını sağlar.',
 'hyoid bone':'Boyunda, alt çenenin altında, at nalı şeklinde küçük bir kemik. Vücuttaki başka hiçbir kemikle doğrudan eklem yapmaz; kaslar ve bağlarla asılı durur, yutma ve konuşmada rol oynar.',
 'sacrum':'Omurganın alt ucunda, beş omurun kaynaşmasıyla oluşan üçgen kemik. Leğen kemiğiyle birleşerek omurgayı pelvise bağlar.',
 'gluteus maximus':'Vücudun en büyük ve en yüzeysel kasıdır; kalça kabarıklığını oluşturur. Kalçayı geriye doğru hareket ettirir, ayakta durma ve merdiven çıkma gibi hareketlerde önemli rol oynar.',
 'sternocleidomastoid':'Boynun yan tarafında, kulak arkasından göğüs ve köprücük kemiğine uzanan kas. Başı döndürür ve öne eğer; her iki taraf birlikte çalıştığında başı öne doğru çeker.',
 'soleus':'Baldırın derininde, gastrocnemius kasının altında bulunan geniş kas. Ayak bileğini aşağı doğru bükerek yürüme ve ayakta durmada dengeyi destekler.',
 'psoas major':'Bel omurlarından başlayıp leğen kemiği içinden geçerek uyluk kemiğine tutunan derin kas. Kalçayı öne doğru büker ve gövdenin duruşunu destekler.',
 'rectus femoris':'Uyluğun ön yüzünde yer alan, quadriceps femoris kas grubunun bir parçası. Hem kalçayı büker hem de dizi düzleştirir.',
 'aortic valve':'Sol karıncık ile aort arasında bulunan, kanın vücuda pompalandıktan sonra kalbe geri kaçmasını önleyen üç yaprakçıklı kapak.',
 'mitral valve':'Sol kulakçık ile sol karıncık arasında bulunan iki yaprakçıklı kapak. Kanın sol kulakçıktan sol karıncığa tek yönlü akmasını sağlar.',
 'tricuspid valve':'Sağ kulakçık ile sağ karıncık arasında bulunan üç yaprakçıklı kapak. Kanın geri kaçmasını önleyerek pulmoner dolaşıma doğru ilerlemesini sağlar.',
 'pulmonary valve':'Sağ karıncık ile akciğer atardamarı arasında yer alan kapak. Kanın akciğerlere pompalandıktan sonra kalbe geri dönmesini engeller.',
 'left eye':'Görme duyusunun organı. Işığı kıran kornea ve lens, görüntüyü algılayan retina ile beyne sinyal ileten optik sinirden oluşan karmaşık bir yapıdır.',
 'right eye':'Görme duyusunun organı. Işığı kıran kornea ve lens, görüntüyü algılayan retina ile beyne sinyal ileten optik sinirden oluşan karmaşık bir yapıdır.',
 'external ear':'Kulak kepçesi ve dış kulak yolundan oluşan, ses dalgalarını toplayıp kulak zarına ileten bölüm.',
 'cornea':'Gözün ön yüzünü örten saydam, kubbe şeklindeki doku. Işığı kırarak gözün odaklama gücünün büyük bölümünü sağlar.',
 'lens':'İrisin arkasında yer alan saydam, esnek yapı. Şeklini değiştirerek farklı uzaklıklardaki nesnelere odaklanmayı sağlar.',
 'pulmonary artery':'Sağ karıncıktan çıkıp akciğerlere oksijensiz kan taşıyan atardamar; vücuttaki oksijence fakir kan taşıyan tek atardamardır.',
 'femoral artery':'Kasığın altından başlayıp uyluk boyunca inen ana atardamar; bacağa kan taşımanın büyük kısmından sorumludur.',
 'coronary artery':'Aortun kökünden çıkıp kalp kasının kendisini besleyen atardamarlar. Tıkanmaları kalp krizine yol açabilir.',
 'common carotid artery':'Boynun ön-yan tarafında yükselen, beyne ve yüze kan taşıyan ana atardamar; nabzı boyundan kolayca hissedilir.',
 'subclavian artery':'Göğüs boşluğundan çıkıp köprücük kemiğinin altından geçerek kola uzanan atardamar; kola ve kısmen beyne kan taşır.',
 'renal artery':'Aorttan çıkarak doğrudan böbreğe giren, böbreği besleyen ve süzülecek kanı ona ulaştıran atardamar.',
 'inferior vena cava':'Karın ve bacaklardan gelen oksijensiz kanı toplayıp sağ kulakçığa taşıyan, vücudun en büyük toplardamarı.',
 'superior vena cava':'Baş, boyun ve kollardan gelen kanı toplayıp sağ kulakçığa taşıyan büyük toplardamar.',
 'portal vein':'Bağırsaklardan, dalaktan ve pankreastan gelen besin açısından zengin kanı doğrudan karaciğere taşıyan özel bir toplardamar.',
 'femoral vein':'Uyluktan gelen kanı toplayıp kalbe doğru taşıyan ana derin toplardamar; femoral arterle birlikte seyreder.',
 'pulmonary vein':'Akciğerlerden oksijenlenmiş kanı sol kulakçığa taşıyan toplardamarlar; vücuttaki oksijence zengin kan taşıyan tek toplardamardır.',
 'internal jugular vein':'Beyin ve yüzden gelen kanı toplayıp boyun boyunca inen, üst ana toplardamara açılan büyük toplardamar.',
 'spinal cord':'Beyinden omurga kanalı içinde aşağı uzanan sinir dokusu şeridi. Beyin ile vücudun geri kalanı arasındaki sinyalleri iletir ve bazı basit refleksleri kendi başına yönetir.',
 'cerebellum':'Beynin arka-alt kısmında yer alan yapı. Denge, kas koordinasyonu ve hareketlerin ince ayarını sağlar.',
 'optic nerve':'Retinadan aldığı görsel bilgiyi beyne taşıyan sinir; ikinci kraniyal sinirdir.',
 'brainstem':'Beyni omurilikle birleştiren yapı; solunum, kalp atışı gibi hayati işlevleri düzenler ve birçok kraniyal sinirin çıkış noktasıdır.',
 'hypothalamus':'Beynin tabanında, talamusun altında yer alan küçük ama etkili bölge. Vücut sıcaklığı, açlık, susuzluk gibi işlevleri düzenler ve hipofiz bezini yöneterek hormon sistemini kontrol eder.',
 'telencephalon':'Beynin en büyük ve en gelişmiş bölümü; iki yarım küreden oluşur. Düşünme, hafıza, dil ve istemli hareket gibi üst düzey işlevlerden sorumludur.',
 'bronchus':'Soluk borusunun akciğerlere girmeden önce ikiye ayrıldığı ana hava yolu dallarından her biri; havayı akciğer içindeki daha küçük dallara taşır.',
 'duodenum':'İnce bağırsağın mideye en yakın, en kısa bölümü. Pankreas ve safra kesesinden gelen sindirim sıvılarının besinlerle karıştığı yerdir.',
 'appendix':'Kalın bağırsağın başlangıcında yer alan, parmak şeklinde küçük bir çıkıntı. Kesin işlevi tartışmalı olsa da bağışıklık dokusu içerdiği düşünülür; iltihaplanması apandisit olarak bilinir.',
 'ureter':'Böbrekten mesaneye idrarı taşıyan ince, kaslı boru; peristaltik hareketlerle idrarı aşağı doğru iter.',
 'urethra':'Mesanedeki idrarın vücut dışına atıldığı son kanal.',
 'thymus':'Göğüs kemiğinin arkasında yer alan, T lenfositlerinin olgunlaştığı organ. Çocuklukta büyük ve aktiftir, yaşla birlikte küçülür.',
 'pituitary gland':'Beynin tabanında, hipotalamusun altında yer alan bezelye büyüklüğünde bez. Büyüme, tiroid işlevi, üreme gibi birçok süreci yöneten hormonlar salgıladığı için "ana bez" olarak da bilinir.',
 'adrenal gland':'Her böbreğin üstünde yer alan küçük bez. Stres yanıtını yöneten adrenalin ile kan basıncı ve elektrolit dengesini etkileyen kortizol gibi hormonlar salgılar.',
 'pineal body':'Beynin ortasında, iki beyin yarım küresi arasında yer alan küçük bez. Uyku-uyanıklık döngüsünü düzenleyen melatonin hormonunu salgılar.',
 'epididymis':'Testisin arkasında yer alan, sıkıca kıvrılmış bir kanal. Testiste üretilen spermlerin olgunlaştığı ve depolandığı yerdir.',
 'seminal vesicle':'Mesanenin arkasında yer alan çift bez; meninin büyük bölümünü oluşturan fruktoz açısından zengin bir sıvı salgılar.',
 'skin':'Vücudun en büyük organı; dış ortama karşı koruyucu bir bariyer oluşturur, sıcaklık düzenlenmesine katkıda bulunur ve dokunma, sıcaklık, ağrı gibi duyuları algılar.',
 'tendon':'Kası kemiğe bağlayan güçlü, esnek olmayan bağ dokusu şeridi. Kasın kasılma kuvvetini kemiğe aktararak hareketi sağlar.',
 'costal cartilage':'Kaburgaların ön uçlarını göğüs kemiğine bağlayan esnek kıkırdak parçası; göğüs kafesinin nefes alırken genişleyip daralmasına olanak tanır.',
 'thyroid cartilage':'Gırtlağın en büyük kıkırdağı; ön çıkıntısı halk arasında "Adem elması" olarak bilinir. Ses tellerini korur ve onlara tutunma yüzeyi sağlar. Tiroid bezinden farklı bir yapıdır.',
};
export function explanation(name:string,system:SystemId){return EXPLANATIONS[name.toLowerCase()] ?? SYSTEMS.find(s=>s.id===system)?.description ?? '';}
// Yaygın aranan yapılar için Türkçe ad + gerçek Latince (Terminologia Anatomica) karşılığı.
// Anahtarlar atlas verisindeki İngilizce adla eşleşir (küçük harf). Sözlükte olmayan yapılar orijinal adıyla gösterilir.
export const STRUCTURE_NAMES:Record<string,{tr:string;latin?:string}> = {
 'heart':{tr:'Kalp',latin:'Cor'},
 'brain':{tr:'Beyin',latin:'Cerebrum'},
 'liver':{tr:'Karaciğer',latin:'Hepar'},
 'stomach':{tr:'Mide',latin:'Gaster'},
 'spleen':{tr:'Dalak',latin:'Lien'},
 'pancreas':{tr:'Pankreas',latin:'Pancreas'},
 'urinary bladder':{tr:'İdrar Kesesi',latin:'Vesica Urinaria'},
 'trachea':{tr:'Soluk Borusu',latin:'Trachea'},
 'diaphragm':{tr:'Diyafram',latin:'Diaphragma'},
 'kidney':{tr:'Böbrek',latin:'Ren'},
 'left kidney':{tr:'Sol Böbrek',latin:'Ren Sinister'},
 'right kidney':{tr:'Sağ Böbrek',latin:'Ren Dexter'},
 'lung':{tr:'Akciğer',latin:'Pulmo'},
 'left lung':{tr:'Sol Akciğer',latin:'Pulmo Sinister'},
 'right lung':{tr:'Sağ Akciğer',latin:'Pulmo Dexter'},
 'esophagus':{tr:'Yemek Borusu',latin:'Oesophagus'},
 'small intestine':{tr:'İnce Bağırsak',latin:'Intestinum Tenue'},
 'large intestine':{tr:'Kalın Bağırsak',latin:'Intestinum Crassum'},
 'colon':{tr:'Kolon',latin:'Colon'},
 'gallbladder':{tr:'Safra Kesesi',latin:'Vesica Biliaris'},
 'thyroid gland':{tr:'Tiroid Bezi',latin:'Glandula Thyroidea'},
 'femur':{tr:'Femur (Uyluk Kemiği)',latin:'Femur'},
 'tibia':{tr:'Tibia (Kaval Kemiği)',latin:'Tibia'},
 'fibula':{tr:'Fibula (Baldır Kemiği)',latin:'Fibula'},
 'humerus':{tr:'Humerus (Pazu Kemiği)',latin:'Humerus'},
 'radius':{tr:'Radius (Önkol Kemiği)',latin:'Radius'},
 'ulna':{tr:'Ulna (Dirsek Kemiği)',latin:'Ulna'},
 'skull':{tr:'Kafatası',latin:'Cranium'},
 'vertebra':{tr:'Omur',latin:'Vertebra'},
 'pelvis':{tr:'Pelvis (Leğen Kemiği)',latin:'Pelvis'},
 'scapula':{tr:'Kürek Kemiği',latin:'Scapula'},
 'clavicle':{tr:'Köprücük Kemiği',latin:'Clavicula'},
 'sternum':{tr:'Göğüs Kemiği',latin:'Sternum'},
 'rib':{tr:'Kaburga',latin:'Costa'},
 'aorta':{tr:'Aort',latin:'Aorta'},
 'larynx':{tr:'Gırtlak',latin:'Larynx'},
 'pharynx':{tr:'Yutak',latin:'Pharynx'},
 'tongue':{tr:'Dil',latin:'Lingua'},
 'eye':{tr:'Göz',latin:'Oculus'},
 'ear':{tr:'Kulak',latin:'Auris'},
 'testis':{tr:'Testis',latin:'Testis'},
 'ovary':{tr:'Yumurtalık',latin:'Ovarium'},
 'uterus':{tr:'Rahim',latin:'Uterus'},
 'prostate':{tr:'Prostat',latin:'Prostata'},
 'patella':{tr:'Diz Kapağı',latin:'Patella'},
 'mandible':{tr:'Alt Çene Kemiği',latin:'Mandibula'},
 'hyoid bone':{tr:'Dil Kemiği',latin:'Os Hyoideum'},
 'sacrum':{tr:'Sağrı Kemiği',latin:'Os Sacrum'},
 'gluteus maximus':{tr:'Büyük Kalça Kası',latin:'M. Gluteus Maximus'},
 'sternocleidomastoid':{tr:'Sternokleidomastoid Kası',latin:'M. Sternocleidomastoideus'},
 'soleus':{tr:'Soleus Kası',latin:'M. Soleus'},
 'psoas major':{tr:'Büyük Bel Kası',latin:'M. Psoas Major'},
 'rectus femoris':{tr:'Uyluk Dik Kası',latin:'M. Rectus Femoris'},
 'aortic valve':{tr:'Aort Kapağı',latin:'Valva Aortae'},
 'mitral valve':{tr:'Mitral Kapak',latin:'Valva Mitralis'},
 'tricuspid valve':{tr:'Triküspit Kapak',latin:'Valva Tricuspidalis'},
 'pulmonary valve':{tr:'Pulmoner Kapak',latin:'Valva Trunci Pulmonalis'},
 'left eye':{tr:'Sol Göz',latin:'Oculus Sinister'},
 'right eye':{tr:'Sağ Göz',latin:'Oculus Dexter'},
 'external ear':{tr:'Dış Kulak',latin:'Auris Externa'},
 'cornea':{tr:'Kornea',latin:'Cornea'},
 'lens':{tr:'Göz Merceği',latin:'Lens'},
 'pulmonary artery':{tr:'Pulmoner Arter',latin:'Arteria Pulmonalis'},
 'femoral artery':{tr:'Femoral Arter',latin:'Arteria Femoralis'},
 'coronary artery':{tr:'Koroner Arter',latin:'Arteria Coronaria'},
 'common carotid artery':{tr:'Ortak Şah Damarı',latin:'Arteria Carotis Communis'},
 'subclavian artery':{tr:'Köprücükaltı Arteri',latin:'Arteria Subclavia'},
 'renal artery':{tr:'Böbrek Atardamarı',latin:'Arteria Renalis'},
 'inferior vena cava':{tr:'Alt Ana Toplardamar',latin:'Vena Cava Inferior'},
 'superior vena cava':{tr:'Üst Ana Toplardamar',latin:'Vena Cava Superior'},
 'portal vein':{tr:'Kapı Toplardamarı',latin:'Vena Portae Hepatis'},
 'femoral vein':{tr:'Femoral Ven',latin:'Vena Femoralis'},
 'pulmonary vein':{tr:'Pulmoner Ven',latin:'Vena Pulmonalis'},
 'internal jugular vein':{tr:'İç Şah Toplardamarı',latin:'Vena Jugularis Interna'},
 'spinal cord':{tr:'Omurilik',latin:'Medulla Spinalis'},
 'cerebellum':{tr:'Beyincik',latin:'Cerebellum'},
 'optic nerve':{tr:'Optik Sinir',latin:'Nervus Opticus'},
 'brainstem':{tr:'Beyin Sapı',latin:'Truncus Encephali'},
 'hypothalamus':{tr:'Hipotalamus',latin:'Hypothalamus'},
 'telencephalon':{tr:'Uç Beyin (Serebrum)',latin:'Telencephalon'},
 'bronchus':{tr:'Bronş',latin:'Bronchus'},
 'duodenum':{tr:'Onikiparmak Bağırsağı',latin:'Duodenum'},
 'appendix':{tr:'Apandis',latin:'Appendix Vermiformis'},
 'ureter':{tr:'Üreter',latin:'Ureter'},
 'urethra':{tr:'Üretra',latin:'Urethra'},
 'thymus':{tr:'Timus Bezi',latin:'Thymus'},
 'pituitary gland':{tr:'Hipofiz Bezi',latin:'Hypophysis'},
 'adrenal gland':{tr:'Böbreküstü Bezi',latin:'Glandula Suprarenalis'},
 'pineal body':{tr:'Epifiz Bezi',latin:'Corpus Pineale'},
 'epididymis':{tr:'Epididim',latin:'Epididymis'},
 'seminal vesicle':{tr:'Seminal Vezikül',latin:'Vesicula Seminalis'},
 'skin':{tr:'Deri',latin:'Cutis'},
 'tendon':{tr:'Kiriş',latin:'Tendo'},
 'costal cartilage':{tr:'Kaburga Kıkırdağı',latin:'Cartilago Costalis'},
 'thyroid cartilage':{tr:'Tiroid Kıkırdağı',latin:'Cartilago Thyroidea'},
};
export function displayName(name:string):{primary:string;secondary?:string}{
 const t=STRUCTURE_NAMES[name.toLowerCase()];
 return t?{primary:t.tr,secondary:t.latin}:{primary:name};
}
